services:
  app:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    image: php:8.3-fpm
    container_name: pametan_klik_app
    working_dir: /var/www
    volumes:
      - .:/var/www
    ports:
      - "9000:9000"
    depends_on:
      - db

  webserver:
    image: nginx:alpine
    container_name: symfony_nginx
    ports:
      - "8000:80"
    volumes:
      - .:/var/www
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app

  db:
    image: mariadb:latest
    container_name: symfony_db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: pametan_klik
      MYSQL_USER: symfony
      MYSQL_PASSWORD: symfony
    ports:
      - "33025:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
